### ISSUE TITLE
qt5 apps crash on debian bullseye

### ISSUE THREAD

**Issue by zanfix** [pelya/xserver-xsdl#151]
Hi all,

I am testing debian bullseye with Xserver XSDL and I noticed that any QT5 application will crash as soon you click on the application window.

There is an example for vlc:

```
zanf@localhost:~$ gdb vlc
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from vlc...
Reading symbols from /usr/lib/debug/.build-id/89/4240474f60635e726afe76d6cf824521ccb6f2.debug...
(gdb) run
Starting program: /usr/bin/vlc 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
VLC media player 3.0.16 Vetinari (revision 3.0.13-8-g41878ff4f2)
[New Thread 0x7fbe53a140 (LWP 10792)]
[New Thread 0x7fbdd39140 (LWP 10793)]
[Thread 0x7fbdd39140 (LWP 10793) exited]
[New Thread 0x7fbd538140 (LWP 10794)]
[New Thread 0x7fbd414140 (LWP 10795)]
[000000555556a5c0] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[New Thread 0x7fb10b2140 (LWP 10796)]
[New Thread 0x7fbdd39140 (LWP 10797)]
[New Thread 0x7fb0abd140 (LWP 10798)]
[New Thread 0x7fa6e89140 (LWP 10799)]
[New Thread 0x7fa6688140 (LWP 10800)]
[New Thread 0x7fa5d12140 (LWP 10801)]
[New Thread 0x7fa5511140 (LWP 10802)]
[New Thread 0x7fa4d10140 (LWP 10803)]
[New Thread 0x7f93fff140 (LWP 10804)]
[New Thread 0x7f937fe140 (LWP 10805)]
[New Thread 0x7fa43d3140 (LWP 10806)]
[New Thread 0x7f7b873140 (LWP 10807)]
[New Thread 0x7f7b072140 (LWP 10808)]
[New Thread 0x7f7a871140 (LWP 10809)]
[New Thread 0x7f7a070140 (LWP 10810)]
[New Thread 0x7f7986f140 (LWP 10811)]
[New Thread 0x7f7906e140 (LWP 10812)]
[New Thread 0x7f7886d140 (LWP 10813)]
[New Thread 0x7f5bfff140 (LWP 10814)]
[New Thread 0x7f5b7fe140 (LWP 10815)]
[New Thread 0x7f5affd140 (LWP 10816)]
[New Thread 0x7f5a7fc140 (LWP 10817)]
[New Thread 0x7f59ffb140 (LWP 10818)]
[New Thread 0x7f597fa140 (LWP 10819)]
[New Thread 0x7f58ff9140 (LWP 10820)]
[New Thread 0x7f43fff140 (LWP 10821)]
[New Thread 0x7f437fe140 (LWP 10822)]
[New Thread 0x7f42ffd140 (LWP 10823)]
[New Thread 0x7f427fc140 (LWP 10824)]
[New Thread 0x7f41ffb140 (LWP 10825)]
[New Thread 0x7f417fa140 (LWP 10826)]
[0000005555609650] main playlist: playlist is empty
qt.qpa.xcb: QXcbConnection: XCB error: 146 (Unknown), sequence: 191, resource id: 0, major code: 139 (Unknown), minor code: 20
qt.qpa.xcb: xcb_shm_create_segment() failed for size 504000

Thread 6 "vlc" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fb10b2140 (LWP 10796)]
0x0000007fbca0fac4 in QWidget::mapFromGlobal(QPoint const&) const () from /lib/aarch64-linux-gnu/libQt5Widgets.so.5
(gdb) bt
#0  0x0000007fbca0fac4 in QWidget::mapFromGlobal(QPoint const&) const () from /lib/aarch64-linux-gnu/libQt5Widgets.so.5
#1  0x0000007fbc9ea290 in QApplication::notify(QObject*, QEvent*) () from /lib/aarch64-linux-gnu/libQt5Widgets.so.5
#2  0x0000007fb3d51460 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/aarch64-linux-gnu/libQt5Core.so.5
#3  0x0000007fbc9e7eb4 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
   from /lib/aarch64-linux-gnu/libQt5Widgets.so.5
#4  0x0000007fbca3b6b4 in ?? () from /lib/aarch64-linux-gnu/libQt5Widgets.so.5
#5  0x0000007fbca3e23c in ?? () from /lib/aarch64-linux-gnu/libQt5Widgets.so.5
#6  0x0000007fbc9e1a80 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/aarch64-linux-gnu/libQt5Widgets.so.5
#7  0x0000007fb3d51460 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/aarch64-linux-gnu/libQt5Core.so.5
#8  0x0000007fbc2f8d84 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /lib/aarch64-linux-gnu/libQt5Gui.so.5
```
Anybody is having this issue? Did somebody find a fix?

Does not happen with sparkle

Bye!

**Comment by zanfix** [comment]
I tried running vlc in Xephyr and it does not crash! it works!

**Comment by Lokawn** [comment]
Not only qt5 apps, LXQt doesn't even start.
